### ISSUE TITLE
How to place calculator under the parent element?

### ISSUE THREAD

**Issue by Mashiane** [kolesnikovav/vuetify-numeric#10]
Hi there

On the codepen, the calculator sits on the top left cornver of the screen. I'm also having a similar issue.

How can I have it sitting just under the parent element when click append is fired?

Thank you

**Comment by Mashiane** [comment]
I took a peek at the codes, perhaps on the click:append method of the textbox, you could also run .updateDimensions so that the rect calculations are redone before the calculator is shown.

Ta!

**Comment by Mashiane** [comment]
Please see this behavior on my side. I think it will be better if when the append icon is clicked, then the position is determined and then the v-numeric is shown under. For now the position of the calculator is fixed once the page is resized.

![Calculator](https://user-images.githubusercontent.com/5799306/96143433-5f1d3400-0f03-11eb-8459-c22455042d96.gif)

**Comment by kolesnikovav** [comment]
@Mashiane Can you give me a link for reproduce?
