### ISSUE TITLE
How to use the "value" property instead of "v-model"

### ISSUE THREAD

**Issue by dontwan** [kolesnikovav/vuetify-numeric#17]
Hi,

First of all thanks for creating this library.

Previously I was using the v-text-field. Now I would like to make more specific use of a number input.
However, I run into a small problem when using this library:
I have a use case where it is not possible for me to use the v-model. With a v-text-field I use the "value" property, however with the v-numeric-input, this property does not work. 

Am I doing something wrong or is this property not supported?

Thanks in advance

**Comment by vcordes79** [comment]
For me it works, but only if I pass a Number, Strings seem not to be supported

**Comment by vcordes79** [comment]
Upon closer examination I realized that the initial value is not set, so it only works dynamically if the value is changed. I created a pull request to fix the issue.
