### ISSUE TITLE
Feature Request: Separation of concerns

### ISSUE THREAD

**Issue by Mashiane** [kolesnikovav/vuetify-numeric#9]
Hi there

Thanks again for the CDN option link. Its working. Can I please make a request.

Lets assume I don't want an outlined text-field yet I want an outlined calculator. How does one separate the two? Perhaps with separate concerns this could work.

For example, the FAB attribute applies ONLY to the calculator and not the text-field. Can you please add an attribute like OUTLINE that will ONLY apply to the calculator and separate from the text-field.

**Comment by kolesnikovav** [comment]
You can use calcStyle object for separate style between calculator & textfield
